In [1]:
from pathlib import Path

import pandas as pd
import geopandas as gpd
from tqdm import tqdm

# Load surveys

In [2]:
raw_dir = Path('../data/dhs/raw')

In [7]:
GEO_COLS = ['DHSYEAR', 'DHSCLUST', 'URBAN_RURA', 'LATNUM', 'LONGNUM', 'DATUM', 'geometry', 'yes', 'no']
SURVEY_COLUMNS = ['hv001', 'hv206']
hr_dfs = dict()

for year_dir in tqdm(raw_dir.iterdir()):
    if year_dir.is_dir():
        year = year_dir.name[3:7]
        for dataset_type_dir in year_dir.iterdir():
            dataset_type = dataset_type_dir.stem[2:4]
            if dataset_type == 'HR':
                for file in dataset_type_dir.iterdir():
                    if file.suffix == '.DTA':
                        survey_df = pd.read_stata(file, columns=SURVEY_COLUMNS)
            """if dataset_type == 'GE':
                for file in dataset_type_dir.iterdir():
                    if file.suffix == '.shp':
                        geo_df = gpd.read_file(file)"""
        survey_df['hv206'] = survey_df['hv206'].str.lower()
        survey_df = survey_df.groupby('hv001')['hv206'].value_counts().unstack()
        #df = geo_df.merge(survey_df, how='outer', left_on='DHSCLUST', right_on='hv001')
        #df[GEO_COLS].to_file(f'{year}.shp')
        #hr_dfs[year] = df[GEO_COLS].copy()
        hr_dfs[year] = survey_df[SURVEY_COLUMNS]

0it [00:03, ?it/s]

KeyError: "None of [Index(['hv001', 'hv206'], dtype='object', name='hv206')] are in the [columns]"

`hv001` is cluster, `hv206` is whether or not there is electricity.

In [6]:
hr_dfs['2008']

,DHSYEAR,DHSCLUST,URBAN_RURA,LATNUM,LONGNUM,DATUM,geometry,yes,no
0,2008.0,1.0,U,13.20103,6.37771,WGS84,POINT (6.37771 13.20103),34.0,4.0
1,2008.0,2.0,U,13.08147,5.26264,WGS84,POINT (5.26264 13.08147),37.0,1.0
2,2008.0,3.0,U,13.06933,5.23022,WGS84,POINT (5.23022 13.06933),40.0,NaN
3,2008.0,4.0,R,13.11720,4.94252,WGS84,POINT (4.94252 13.11720),4.0,33.0
4,2008.0,5.0,R,12.84140,5.09136,WGS84,POINT (5.09136 12.84140),NaN,41.0
...,...,...,...,...,...,...,...,...,...
881,2008.0,884.0,R,6.76871,3.64365,WGS84,POINT (3.64365 6.76871),1.0,40.0
882,2008.0,885.0,R,6.70765,3.48796,WGS84,POINT (3.48796 6.70765),22.0,19.0
883,2008.0,886.0,R,7.23515,3.00508,WGS84,POINT (3.00508 7.23515),18.0,16.0
884,2008.0,887.0,R,7.19138,2.96943,WGS84,POINT (2.96943 7.19138),NaN,38.0
885,2008.0,888.0,R,6.85844,3.03110,WGS84,POINT (3.03110 6.85844),39.0,1.0